management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 7001

spring:
  application:
    name: customer-service
  cloud:
    consul:
      host: localhost
      port: 8500
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8181/auth/realms/ccc-realm"

