management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 0

spring:
  application:
    name: order-service
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}-${random.int(1,19999)}
        health-check-path: /actuator/health
        health-check-interval: 20s
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8181/auth/realms/ccc-realm"
