spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8181/auth/realms/ccc-realm
        registration:
          spring-cloud-gateway-client:
            provider: keycloak
            client-id: spring-cloud-gateway-client
            client-secret: a73f378d-f6ca-49e4-b860-4710bfdc9cd2
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9080/login/oauth2/code/spring-cloud-gateway-client
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - TokenRelay
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
server:
  port: 9080
